logger:
  level: info

storage:
  provider: postgres
  dsn: user=postgres password=test dbname=calendar host=localhost port=5432 sslmode=disable
  retry: 5

broker:
  dsn: amqp://guest:guest@localhost:5672
  queue: remind

remind:
  freq: 1s