version: '3.7'

services:
  db:
    image: postgres:alpine
    container_name: calendar_db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: calendar
    ports:
      - 5432:5432

  rabbitmq:
    container_name: calendar_amqp
    image: rabbitmq
    restart: on-failure
    command: rabbitmq-server
    ports:
      - 5672

  api:
    container_name: calendar_api
    build: api
    restart: on-failure
    ports:
      - 50051:50051
    depends_on:
      - db
      - rabbitmq

  reminder:
    container_name: calendar_reminder
    build: reminder
    restart: on-failure
    ports:
      - 5672:5672
    depends_on:
      - db
      - rabbitmq

  notifier:
    container_name: calendar_notifier
    build: notifier
    restart: on-failure
    ports:
      - 5672:5672
    depends_on:
      - db
      - rabbitmq

