version: '3.7'

networks:
  net:

services:
  db:
    image: postgres:alpine
    container_name: calendar_db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: calendar
    networks:
      - net

  rabbitmq:
    container_name: calendar_amqp
    image: rabbitmq
    restart: on-failure
    command: rabbitmq-server
    networks:
      - net

  api:
    container_name: calendar_api
    build: api/
    restart: on-failure
    depends_on:
      - db
      - rabbitmq
    networks:
      - net

  reminder:
    build: reminder/
    restart: on-failure
    container_name: calendar_reminder
    depends_on:
      - db
      - rabbitmq
    networks:
      - net

  notifier:
    container_name: calendar_notifier
    restart: on-failure
    build: notifier/
    depends_on:
      - db
      - rabbitmq
    networks:
      - net