# build stage
FROM golang:alpine as builder
RUN apk add git
WORKDIR /github.com/IamStubborN/calendar/notifier
COPY . .
ENV GO111MODULE=on
ENV CGO_ENABLED=0
RUN go build -o notifier ./cmd

# final stage
FROM alpine:latest
WORKDIR /root/petstore/
COPY --from=builder /github.com/IamStubborN/calendar/notifier .
COPY --from=builder /github.com/IamStubborN/calendar/notifier/config.yaml .

ENTRYPOINT ["./notifier"]