logger:
  level: info

storage:
  provider: postgres
  dsn: user=postgres password=test dbname=calendar host=calendar_db port=5432 sslmode=disable
  retry: 20

broker:
  dsn: amqp://guest:guest@calendar_amqp:5672
  queue: remind

remind:
  freq: 1s